### PR TITLE
feat(topics): added topic 12 animation

### PR DESCRIPTION
**Pull request by Lazurite259**
#99 
The animation is now using the functions in canvas.js.

### CODE REVIEW

**Comment by Lazurite259** [comment]
The issue that vertices might be out of boundary is not solved yet.

**Comment by Kiyo5hi** [comment]
Do you plan to merge this commit before the issue is resolve or after? We can do either.

**Comment by Lazurite259** [comment]
I will add some information on the graph later. We can merge it after I added them on.

**Review by ZhiqinLuUCI — APPROVED** [review]
Good!

**Pull request merged**
